DATASETS:
  CRPD: './data/CRPD'
  CCPD: './data/CCPD2020/ccpd_green'
  save_dataset: './data/CCPD_processed/'
  save_results: './results'
  test_folder: './test_imgs'
  str2int:  [{"皖": 0, "沪": 1, "津": 2, "渝": 3, "冀": 4, "晋": 5, "蒙": 6, "辽": 7, "吉": 8, "黑": 9, "苏": 10,
            "浙": 11, "京": 12, "闽": 13, "赣": 14, "鲁": 15, "豫": 16, "鄂": 17, "湘": 18, "粤": 19, "桂": 20, "琼": 21,
            "川": 22, "贵": 23, "云": 24, "藏": 25, "陕": 26, "甘": 27, "青": 28, "宁": 29, "新": 30},
            {"A" : 0, "B" : 1, "C" : 2, "D" : 3, "E" : 4, "F" : 5, "G" : 6, "H" : 7, "J" : 8, "K" : 9, "L" : 10, "M" : 11,
              "N" : 12, "P" : 13, "Q" : 14, "R" : 15, "S" : 16, "T" : 17, "U" : 18, "V" : 19, "W" : 20, "X":  21, "Y" : 22,
              "Z" : 23, "0" : 24, "1" : 25, "2" : 26, "3" : 27, "4" : 28, "5" : 29, "6" : 30, "7" : 31, "8" : 32, "9" : 33}]

MODEL:
  name: 'chinese_ocr_db_crnn_server'
  det_model_dir: './models/det_ppocr_v3_finetune/infer'
  rec_model_dir: './models/rec_ppocr_v3_finetune/infer'
  test_cfg:
    # TODO: improve
    batch_size: 1

IP_CAMERA:
  url: 'http://admin:admin@192.168.1.103:8081'